Change go-ci.yml

diff --git a/.github/workflows/go-ci.yml b/.github/workflows/go-ci.yml
--- a/.github/workflows/go-ci.yml
+++ b/.github/workflows/go-ci.yml
@@ -2,110 +2,375 @@ name: "Go CI/CD Pipeline"
 
 on:
   workflow_call:
+    secrets:
+      AZURE_STORAGE_ACCOUNT_NAME:
+        description: "Azure Storage Account Name"
+        required: true
+      AZURE_STORAGE_ACCOUNT_KEY:
+        description: "Azure Storage Account Key"
+        required: true
+      OPENAI_API_KEY:
+        description: "OpenAI API Key"
+        required: true
     inputs:
       go-version:
-        description: 'La versión de Go para usar en este pipeline'
+        description: "La versión de Go para usar en este pipeline"
         required: true
         type: string
       language:
-        description: 'El lenguaje de programación para usar en este pipeline'
+        description: "El lenguaje de programación para usar en este pipeline"
         required: true
         type: string
       project-path:
-        description: 'La ruta del proyecto donde se encuentra el código Go'
+        description: "La ruta del proyecto donde se encuentra el código Go"
         required: true
         type: string
+      requirements-path:
+        description: "La ruta del proyecto donde se encuentran los requisitos del proyecto Python"
+        required: false
+        type: string
       build-configuration:
-        description: 'Configuración de build (Debug o Release)'
+        description: "Configuración de build (Debug o Release)"
         required: true
         type: string
       additional-install-commands:
-        description: 'Comandos adicionales para instalar dependencias antes de construir'
+        description: "Comandos adicionales para instalar dependencias antes de construir"
+        required: false
+        type: string
+      build-command:
+        description: "Comando personalizado para construir el proyecto"
+        required: false
+        type: string
+      report-language:
+        description: "Idioma en el que se generará el informe (por ejemplo: English, Spanish, etc.)"
         required: false
         type: string
       run-check-code-format:
-        description: 'Ejecutar la verificación del formato del código'
+        description: "Ejecutar la verificación del formato del código"
         required: true
         type: boolean
       run-code-analysis:
-        description: 'Ejecutar el análisis de código'
+        description: "Ejecutar el análisis de código"
         required: true
         type: boolean
       run-lint:
-        description: 'Ejecutar Lint'
+        description: "Ejecutar Lint"
         required: true
         type: boolean
       environment-variables:
-        description: 'Variables de entorno para configurar en el pipeline (formato: "VAR1=value1, VAR2=value2")'
+        description: "Variables de entorno para configurar en el pipeline (formato: 'VAR1=value1, VAR2=value2')"
         required: false
         type: string
 
 jobs:
   # Job principal para construir el proyecto Go
   ci_pipeline:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04
+    outputs:
+      error-detected: ${{ steps.analyze.outputs.error-detected || 'success' }}
     steps:
+      - name: Initialize error-detected
+        run: echo "error-detected=success" >> $GITHUB_ENV
+
+      - name: Debug OS Version
+        run: lsb_release -a || cat /etc/os-release
+        continue-on-error: true
+
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: Set up Go
         uses: actions/setup-go@v2
         with:
           go-version: ${{ inputs.go-version }}
 
-      - name: Install additional dependencies
-        if: ${{ inputs.additional-install-commands }}
-        run: ${{ inputs.additional-install-commands }}
+      - name: Set Azure Environment Variables
+        run: |
+          echo "AZURE_STORAGE_ACCOUNT_NAME=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" >> $GITHUB_ENV
+          echo "AZURE_STORAGE_ACCOUNT_KEY=${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}" >> $GITHUB_ENV
 
-      - name: Install dependencies
-        run: go mod tidy
+      - name: Set OpenAI API Key
+        run: |
+          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
+
+      - name: Verify Secrets
+        run: |
+          echo "Azure Account Name: ${AZURE_STORAGE_ACCOUNT_NAME}"
+          echo "Azure Account Key: ${AZURE_STORAGE_ACCOUNT_KEY}"
+          echo "OpenAI API Key: ${OPENAI_API_KEY}"
 
       - name: Set Environment Variables
         if: ${{ inputs.environment-variables }}
         run: |
+          echo "Setting environment variables"
           IFS=',' read -ra VARS <<< "${{ inputs.environment-variables }}"
           for VAR in "${VARS[@]}"; do
             echo "Setting $VAR"
             echo "$VAR" >> $GITHUB_ENV
           done
 
-      - name: Build
-        run: go build -o output/app ${{ inputs.project-path }}
+      - name: Install additional dependencies
+        if: ${{ inputs.additional-install-commands }}
+        run: |
+          echo "Running additional install commands"
+          mkdir -p "${GITHUB_WORKSPACE}/logs"
+          repo_name=$(basename "${{ github.repository }}")
+          ${{ inputs.additional-install-commands }} 2>&1 | tee "${GITHUB_WORKSPACE}/logs/${repo_name}-${{ github.run_id }}-additional_install.log"
+          if [ ! -f "${GITHUB_WORKSPACE}/logs/${repo_name}-${{ github.run_id }}-additional_install.log" ]; then
+            echo "ERROR : Log file for additional dependencies installation was not created!" >&2
+            exit 1
+          else
+            echo "SUCCESS : Log file for additional dependencies installation was created!" >&2
+          fi
 
-  # Job separado para formatear código
+      - name: Install dependencies and Save Logs for Go
+        run: |
+          mkdir -p "${GITHUB_WORKSPACE}/logs"
+
+          # Variables dinámicas
+          repo_name=$(basename "${GITHUB_REPOSITORY}")
+          log_file="${GITHUB_WORKSPACE}/logs/${repo_name}-${{ github.run_id }}-go-dependencies.log"
+
+          # Instalación de dependencias
+          if [ -f "go.mod" ]; then
+            echo "Installing dependencies using go.mod"
+            go mod tidy 2>&1 | tee "$log_file"
+          else
+            echo "No go.mod file found. Skipping dependency installation." 2>&1 | tee "$log_file"
+          fi
+
+          # Verificación de creación del log
+          if [ ! -f "$log_file" ]; then
+            echo "ERROR: Log file $log_file was not created!" >&2
+            exit 1
+          else
+            echo "SUCCESS: Log file $log_file was created!" >&2
+          fi
+
+      - name: Set Environment Variables
+        if: ${{ inputs.environment-variables }}
+        run: |
+          echo "Setting environment variables"
+          IFS=',' read -ra VARS <<< "${{ inputs.environment-variables }}"
+          for VAR in "${VARS[@]}"; do
+            echo "Setting $VAR"
+            echo "$VAR" >> $GITHUB_ENV
+          done
+
+      - name: Build Go Project and Save Logs
+        id: build
+        run: |
+          echo "Building Go project"
+          repo_name=$(basename "${GITHUB_REPOSITORY}")
+          mkdir -p "${GITHUB_WORKSPACE}/logs"
+          log_file="${GITHUB_WORKSPACE}/logs/${repo_name}-${{ github.run_id }}-build.log"
+
+          # Verificar si se proporciona un comando de build personalizado
+          if [ -n "${{ inputs.build-command }}" ]; then
+              echo "Using custom build command"
+              ${{ inputs.build-command }} 2>&1 | tee "$log_file"
+              if [ ${PIPESTATUS[0]} -ne 0 ]; then
+                  echo "ERROR: Custom build command failed!" >&2
+                  exit 1
+              fi
+          else
+              echo "Building with default Go build command"
+              go build -o output/app ${{ inputs.project-path }} 2>&1 | tee "$log_file"
+              if [ ${PIPESTATUS[0]} -ne 0 ]; then
+                  echo "ERROR: Go build failed!" >&2
+                  exit 1
+              fi
+          fi
+
+          # Verificar errores en los logs
+          if grep -q "ERROR" "$log_file"; then
+              echo "ERROR: Found 'ERROR' in build logs!" >&2
+              exit 1
+          fi
+
+          # Confirmar la creación del log
+          if [ ! -f "$log_file" ]; then
+              echo "ERROR: Log file $log_file was not created!" >&2
+              exit 1
+          else
+              echo "SUCCESS: Log file $log_file was created!" >&2
+          fi
+        continue-on-error: true
+
+      - name: Move Go binary to workspace
+        id: move-go-binary
+        run: |
+          echo "GITHUB_WORKSPACE is: ${GITHUB_WORKSPACE}"
+          echo "Searching for Go binary files in the output directory..."
+          GO_BINARY=$(find "${GITHUB_WORKSPACE}/output/" -type f -name "app")
+          if [ -n "$GO_BINARY" ]; then
+            echo "Go binary file found: $GO_BINARY"
+            mkdir -p "${GITHUB_WORKSPACE}/dist"
+            mv "$GO_BINARY" "${GITHUB_WORKSPACE}/dist/"
+            if [ -f "${GITHUB_WORKSPACE}/dist/$(basename $GO_BINARY)" ]; then
+              echo "SUCCESS: Go binary file moved to dist directory."
+              echo "file-exists=true" >> $GITHUB_OUTPUT
+            else
+              echo "ERROR: Failed to move the Go binary file." >&2
+              echo "file-exists=false" >> $GITHUB_OUTPUT
+              exit 1
+            fi
+          else
+            echo "WARNING: No Go binary file found in the output directory. Skipping artifact upload." >&2
+            echo "file-exists=false" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Upload Go build artifact
+        uses: actions/upload-artifact@v4
+        if: steps.move-go-binary.outputs.file-exists == 'true'  # Condición basada en la salida
+        with:
+          name: ${{ github.event.repository.name }}-${{ github.run_id }}
+          path: ${{ github.workspace }}/dist/app
+          if-no-files-found: ignore
+
+      - name: Debug Logs Directory
+        if: always()
+        run: |
+          echo "Current working directory: $(pwd)"
+          echo "Listing contents of the current directory:"
+          ls -la
+          echo "Listing contents of the GITHUB_WORKSPACE directory:"
+          ls -la $GITHUB_WORKSPACE
+          echo "Checking if the logs directory exists in the workspace:"
+          if [ -d "$GITHUB_WORKSPACE/logs" ]; then
+            echo "Logs directory exists in the workspace."
+            ls -la $GITHUB_WORKSPACE/logs
+          else
+            echo "ERROR: Logs directory does not exist in the workspace!"
+          fi      
+     
+      # Paso para verificar si el nombre de la cuenta de almacenamiento está configurado
+      - name: Debug Storage Account Name
+        if: always()
+        run: |
+          echo "Checking if AZURE_STORAGE_ACCOUNT_NAME is set..."
+          if [ -z "${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" ]; then
+            echo "ERROR: AZURE_STORAGE_ACCOUNT_NAME is not set." >&2
+            exit 1
+          else
+            echo "Account Name: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}"
+          fi
+
+      - name: Verify Logs Directory
+        if: always()
+        run: |
+          if [ -d "$GITHUB_WORKSPACE/logs" ] && [ "$(ls -A $GITHUB_WORKSPACE/logs)" ]; then
+            echo "Logs directory exists and contains files:"
+            ls -la $GITHUB_WORKSPACE/logs
+          else
+            echo "ERROR: Logs directory is empty or does not exist!" >&2
+            exit 1
+          fi
+      
+      # Paso para subir los logs al contenedor de Azure Storage
+      - name: Upload Logs to Azure Storage
+        if: always()
+        run: |
+          if [ -d "$GITHUB_WORKSPACE/logs" ]; then
+            for log in $GITHUB_WORKSPACE/logs/*.log; do
+              echo "Uploading $log to Azure Storage..."
+              az storage blob upload --account-name "${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" \
+                                    --account-key "${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}" \
+                                    --container-name logs \
+                                    --file "$log" \
+                                    --name "$(basename $log)" \
+                                    --overwrite
+            done
+          else
+            echo "ERROR: Logs directory does not exist. Skipping upload." >&2
+            exit 1
+          fi
+      
+      - name: Initialize error-detected
+        if: always()
+        run: echo "error-detected=false" >> $GITHUB_ENV
+      
+      - name: Debug needs output
+        if: always()
+        run: |
+          echo "Output from ci_pipeline: ${{ needs.ci_pipeline.outputs.error-detected }}"
+
+      - name: Debug analyze_failed_logs input
+        if: always()
+        run: |
+          echo "Error-detected from ci_pipeline: ${{ needs.ci_pipeline.outputs.error-detected }}"
+          echo "Nueva variable input error-detected : ${{ inputs.error-detected }}"
+      
+      - name: Verify and analyze logs for errors
+        id: analyze
+        if: always()
+        run: |
+          echo "Analyzing logs for errors..."
+          repo_name=$(basename "${{ github.repository }}")
+          log_file="${GITHUB_WORKSPACE}/logs/${repo_name}-${{ github.run_id }}-build.log"
+
+          if [ -f "$log_file" ]; then
+            if grep -qi "error" "$log_file"; then
+              echo "Errors found in logs."
+              echo "error-detected=failure" >> $GITHUB_ENV
+              echo "error-detected=failure" >> $GITHUB_OUTPUT
+            else
+              echo "No errors found."
+              echo "error-detected=success" >> $GITHUB_ENV
+              echo "error-detected=success" >> $GITHUB_OUTPUT
+            fi
+          else
+            echo "ERROR: Build log file not found!" >&2
+            echo "error-detected=failure" >> $GITHUB_ENV
+            echo "error-detected=failure" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Debug error-detected
+        run: |
+          echo "error-detected (from ENV): ${{ env.error-detected }}"
+          echo "error-detected (from OUTPUT): ${{ steps.analyze.outputs.error-detected || 'not set' }}"
+  
+      - name: Debug final error-detected
+        if: always()
+        run: |
+          echo "Final error-detected value (from ENV): ${{ inputs.error-detected }} || 'not set' }}"
+          echo "Final error-detected value (from OUTPUT): ${{ steps.analyze.outputs.error-detected || 'not set' }}"
+        
+  # Job separado para formatear código y recopilar logs
   check-code-format:
+    name: Check Code Format
     needs: ci_pipeline
     if: ${{ inputs.run-check-code-format }}
     uses: ./.github/workflows/check-code-format.yml
+    secrets:
+      AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
+      AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
     with:
       language: ${{ inputs.language }}
       go-version: ${{ inputs.go-version }}
+      project-path: ${{ inputs.project-path }}
 
-  # Job separado para análisis de código
   code-analysis:
+    name: Code Analysis
     needs: ci_pipeline
     if: ${{ inputs.run-code-analysis }}
     uses: ./.github/workflows/scan-security-vulnerabilities.yml
+    secrets:
+      AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
+      AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
     with:
       language: ${{ inputs.language }}
       go-version: ${{ inputs.go-version }}
       project-path: ${{ inputs.project-path }}
 
-  # Job separado para generar artefacto de build
-  build-artifact:
-    needs: ci_pipeline
-    if: ${{ inputs.run-build-artifact }}
-    uses: ./.github/workflows/build-artifact.yml
-    with:
-      language: ${{ inputs.language }}
-      go-version: ${{ inputs.go-version }}
-      project-path: ${{ inputs.project-path }}
-
-  # Job separado para ejecutar Lint
   go-lint:
+    name: Go Linter
     needs: ci_pipeline
     if: ${{ inputs.run-lint }}
     uses: ./.github/workflows/lint.yml
+    secrets:
+      AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
+      AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
     with:
       language: ${{ inputs.language }}
       go-version: ${{ inputs.go-version }}
