Move code to different yml

diff --git a/.github/workflows/python-ci.yml b/.github/workflows/python-ci.yml
--- a/.github/workflows/python-ci.yml
+++ b/.github/workflows/python-ci.yml
@@ -216,10 +216,10 @@ jobs:
           else
               echo "SUCCESS: Log file $log_file was created!" >&2
           fi
-        continue-on-error: true
+        continue-on-error: false
 
       - name: Move wheel file to workspace
-        id: move-wheel  # Agrega un ID para referenciar el paso
+        id: move-wheel  
         run: |
           echo "GITHUB_WORKSPACE is: ${GITHUB_WORKSPACE}"
           echo "Searching for wheel files..."
@@ -307,26 +307,26 @@ jobs:
             exit 1
           fi
       
-      - name: Debug Pipeline Status
-        if: always()
+      - name: Verify and analyze logs for errors
+        id: analyze
         run: |
-          echo "Pipeline Status: ${{ steps.set-status.outputs.pipeline-status }}"
-
-      - name: Set CI Pipeline Result
-        if: always()
-        id: set-status
-        run: |
-          if [ "$GITHUB_STATUS" = "failure" ]; then
-            echo "pipeline-status=failure" >> $GITHUB_OUTPUT
+          echo "Analyzing logs for 'ERROR:' keyword..."
+          LOGS_FOUND=$(grep -rl "ERROR:" $GITHUB_WORKSPACE/logs || true)
+          if [ -n "$LOGS_FOUND" ]; then
+            echo "Errors found in logs:"
+            echo "$LOGS_FOUND"
+            echo "error-detected=true" >> $GITHUB_OUTPUT
+            exit 1  # Configura el job como 'failure'
           else
-            echo "pipeline-status=success" >> $GITHUB_OUTPUT
+            echo "No errors found in logs."
+            echo "error-detected=false" >> $GITHUB_OUTPUT
           fi
 
   # Job separado para formatear código y recopilar logs
   check-code-format:
     name: Check Code Format
     needs: ci_pipeline
-    if: ${{ inputs.run-check-code-format }}
+    if: ${{ inputs.run-check-code-format }} && ${{ needs.ci_pipeline.result == 'success' }}
     uses: ./.github/workflows/check-code-format.yml
     secrets:
       AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
@@ -339,7 +339,7 @@ jobs:
   code-analysis:
     name: Code Analysis
     needs: ci_pipeline
-    if: ${{ inputs.run-code-analysis }}
+    if: ${{ inputs.run-code-analysis }} && ${{ needs.ci_pipeline.result == 'success' }}
     uses: ./.github/workflows/scan-security-vulnerabilities.yml
     secrets:
       AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
@@ -352,7 +352,7 @@ jobs:
   python-lint:
     name: Python Linter
     needs: ci_pipeline
-    if: ${{ inputs.run-lint }}
+    if: ${{ inputs.run-lint }} && ${{ needs.ci_pipeline.result == 'success' }}
     uses: ./.github/workflows/lint.yml
     secrets:
       AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
@@ -363,7 +363,7 @@ jobs:
 
   analyze_failed_logs:
     name: Analyze Failed Logs
-    needs: [ci_pipeline]
+    needs: ci_pipeline
     if: ${{ needs.ci_pipeline.result == 'failure' }}
     uses: ./.github/workflows/analyze-logs.yml
     secrets:
