Move code to different yml

diff --git a/.github/workflows/python-ci.yml b/.github/workflows/python-ci.yml
--- a/.github/workflows/python-ci.yml
+++ b/.github/workflows/python-ci.yml
@@ -82,7 +82,7 @@ jobs:
   ci_pipeline:
     runs-on: ubuntu-24.04
     outputs:
-      error-detected: ${{ steps.set-error-detected.outputs.error-detected }}
+      error-detected: ${{ env.error-detected }}
     steps:
       - name: Debug OS Version
         run: lsb_release -a || cat /etc/os-release
@@ -312,19 +312,25 @@ jobs:
         if: always()
         run: |
           echo "Analyzing logs for errors..."
-          if grep -qi "error" build.log; then
-            echo "Errors found in logs."
-            echo "error-detected=true" >> $GITHUB_ENV
-            echo "::set-output name=error-detected::true"
+          repo_name=$(basename "${{ github.repository }}")
+          log_file="${GITHUB_WORKSPACE}/logs/${repo_name}-${{ github.run_id }}-build.log"
+          
+          if [ -f "$log_file" ]; then
+            if grep -qi "error" "$log_file"; then
+              echo "Errors found in logs."
+              echo "error-detected=true" >> $GITHUB_ENV
+            else
+              echo "No errors found."
+              echo "error-detected=false" >> $GITHUB_ENV
+            fi
           else
-            echo "No errors found."
+            echo "ERROR: Build log file not found!" >&2
             echo "error-detected=false" >> $GITHUB_ENV
-            echo "::set-output name=error-detected::false"
           fi
 
       - name: Debug error-detected output
         if: always()
-        run: echo "error-detected=${{ steps.analyze.outputs.error-detected }}"
+        run: echo "error-detected=${{ env.error-detected }}"
         
   # Job separado para formatear código y recopilar logs
   check-code-format:
