Modify go yml and analyze_logs.py

diff --git a/.github/workflows/python-ci.yml b/.github/workflows/python-ci.yml
--- a/.github/workflows/python-ci.yml
+++ b/.github/workflows/python-ci.yml
@@ -243,26 +243,20 @@ jobs:
             ls -la $GITHUB_WORKSPACE/logs
           else
             echo "ERROR: Logs directory does not exist in the workspace!"
-          fi
+          fi      
+     
+      # - name: Upload Logs to Azure Storage
+      #   run: |
+      #     if [ -d "$GITHUB_WORKSPACE/logs" ]; then
+      #       for log in $GITHUB_WORKSPACE/logs/*.log; do
+      #         az storage blob upload --account-name "$AZURE_STORAGE_ACCOUNT_NAME" --account-key "$AZURE_STORAGE_ACCOUNT_KEY" --container-name logs --file "$log" --name "$(basename $log)"
+      #       done
+      #     else
+      #       echo "ERROR: Logs directory does not exist. Skipping upload." >&2
+      #       exit 1
+      #     fi
       
-      - name: Upload Logs Artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: logs
-          path: $GITHUB_WORKSPACE/logs
-      
-      - name: Upload Logs to Azure Storage
-        run: |
-          if [ -d "$GITHUB_WORKSPACE/logs" ]; then
-            for log in $GITHUB_WORKSPACE/logs/*.log; do
-              az storage blob upload --account-name "$AZURE_STORAGE_ACCOUNT_NAME" --account-key "$AZURE_STORAGE_ACCOUNT_KEY" --container-name logs --file "$log" --name "$(basename $log)"
-            done
-          else
-            echo "ERROR: Logs directory does not exist. Skipping upload." >&2
-            exit 1
-          fi
-      
-            # Paso para verificar si el nombre de la cuenta de almacenamiento está configurado
+      # Paso para verificar si el nombre de la cuenta de almacenamiento está configurado
       - name: Debug Storage Account Name
         run: |
           echo "Checking if AZURE_STORAGE_ACCOUNT_NAME is set..."
@@ -289,7 +283,13 @@ jobs:
             echo "ERROR: Logs directory is empty or does not exist!" >&2
             exit 1
           fi
-        
+      
+      - name: Upload Logs Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: logs
+          path: $GITHUB_WORKSPACE/logs
+      
       # Paso para subir los logs al contenedor de Azure Storage
       - name: Upload Logs to Azure Storage
         run: |
