Change route of logs

diff --git a/.github/workflows/python-ci.yml b/.github/workflows/python-ci.yml
--- a/.github/workflows/python-ci.yml
+++ b/.github/workflows/python-ci.yml
@@ -84,16 +84,31 @@ jobs:
           mkdir -p "${GITHUB_WORKSPACE}/logs"
           repo_name=$(basename "${{ github.repository }}")
           ${{ inputs.additional-install-commands }} 2>&1 | tee "${GITHUB_WORKSPACE}/logs/${repo_name}-${{ github.run_id }}-additional_install.log"
+          if [ ! -f "${GITHUB_WORKSPACE}/logs/${repo_name}-${{ github.run_id }}-additional_install.log" ]; then
+            echo "ERROR : Log file for additional dependencies installation was not created!" >&2
+            exit 1
+          else
+            echo "SUCCESS : Log file for additional dependencies installation was created!" >&2
+          fi
         
       - name: Install dependencies
         run: |
           echo "Installing dependencies"
+          mkdir -p "${GITHUB_WORKSPACE}/logs"
+          repo_name=$(basename "${{ github.repository }}")
           if [ -f "${{ inputs.requirements-path }}requirements.txt" ]; then
-            pip install -r ${{ inputs.requirements-path }}requirements.txt 2>&1 | tee "${{ github.repository }}-${{ github.run_id }}-dependencies.log"
+            pip install -r ${{ inputs.requirements-path }}requirements.txt 2>&1 | tee "${GITHUB_WORKSPACE}/logs/${repo_name}-${{ github.run_id }}-dependencies.log"
           elif [ -f "${{ inputs.project-path }}pyproject.toml" ]; then
-            pip install . 2>&1 | tee "${{ github.repository }}-${{ github.run_id }}-dependencies.log"
+            pip install . 2>&1 | tee "${GITHUB_WORKSPACE}/logs/${repo_name}-${{ github.run_id }}-dependencies.log"
           else
-            echo "No requirements or pyproject.toml file found. Skipping dependency installation." 2>&1 | tee "${{ github.repository }}-${{ github.run_id }}-dependencies.log"
+            echo "No requirements or pyproject.toml file found. Skipping dependency installation." 2>&1 | tee "${GITHUB_WORKSPACE}/logs/${repo_name}-${{ github.run_id }}-dependencies.log"
+          fi
+          if [ ! -f "${GITHUB_WORKSPACE}/logs/${repo_name}-${{ github.run_id }}-dependencies.log" ]; then
+            echo "ERROR : Log file for dependencies installation was not created!" >&2
+            exit 1
+          else
+            echo "SUCCESS : Log file for dependencies installation was created!" >&2
+          fi
 
       - name: Set Environment Variables
         if: ${{ inputs.environment-variables }}
